### ISSUE TITLE
Authenticating with a Google ID from an invalid host domain prevents reauthentication

### ISSUE THREAD

**Issue by B3rry** [amida-tech/ration#14]
Once authenticated with a Google ID from an invalid host, a user is unable to re-authenticate with another Google ID

**Comment by jsachs** [comment]
@B3rry what were your steps to reproduce? I tested locally and the passport auth prevents me from ever becoming authenticated with an invalid host.

**Comment by B3rry** [comment]
Sorry, just seeing you mentioned me in this. When authenticating, if I have multiple google accounts already authenticated, I can select from any of them. In this instance, using my google apps account *@jonberry.co, provides me the error below. Although it looks like you've now re-added the sign-in prompt. So this issue may be resolved. Before, it was returning the error seen in the screenshot provided, but not the ability to try and authenticate again.

<img width="550" alt="screen shot 2016-12-01 at 12 49 16 am" src="https://cloud.githubusercontent.com/assets/5562161/20783221/67ca8818-b760-11e6-81a7-1ca0861dd8ed.png">
<img width="1254" alt="screen shot 2016-12-01 at 12 50 35 am" src="https://cloud.githubusercontent.com/assets/5562161/20783222/67cc8fbe-b760-11e6-84aa-8ef75b68c032.png">

**Comment by jsachs** [comment]
Yeah, I'm not sure if there's a way to restrict your visible domains, but it is supposed to throw an error if you use anything other than an amida address.
