### ISSUE TITLE
use passport to authenticate admin status on delegation.

### ISSUE THREAD

**Issue by mmccall** [amida-tech/ration#37]
Does a DB check now, should standardize to the passport way of doing things.

**Comment by jsachs** [comment]
Yeah, the more you use it, the more you realize how amazing it is to just chain all of your functionality through middleware.

**Comment by jsachs** [comment]
Closed by #39?

**Comment by mmccall** [comment]
no, it's still out there, I'm doing an extra DB lookup I need to fix.
