### ISSUE TITLE
Add ability for admin to delete users.

### ISSUE THREAD

**Issue by mmccall** [amida-tech/ration#42]
The API already exists (you can delete your own account), just need to extend it for admins.

Also, user admin API is getting crowded with buttons, and could use a cleanup, and modal confirmations for actions.

**Comment by jsachs** [comment]
Please no modals. Something like this? https://github.com/stefanocudini/bootstrap-confirm-button

**Comment by mmccall** [comment]
challenge accepted.

**Comment by jsachs** [comment]
Closed by cd1b46b1f43c65901ced1d8cd903f44339858229
