### ISSUE TITLE
Add ability to 'activate' inactive users.

### ISSUE THREAD

**Issue by mmccall** [amida-tech/ration#43]
There is no way to bring them back once they are deactivated.

**Comment by jsachs** [comment]
@mmccall Do we want to allow this through a UI? This seems like the sort of thing reserved for a `superadmin`. I haven't seen many applications that allow reactivation of users. I can understand the use case, such as an employee returning or taking a sabbatical, but it seems like it should be reserved for a db admin or root user.

**Comment by mmccall** [comment]
I don't think it's a priority right now, I just wanted to make sure that we captured that this wasn't there. I was thinking of inactivation/activate as a temporary thing like you mentioned so people could or couldn't show up in the reports.  For instance, if you have an contractor that you use infrequently.  That is something I think you would want an admin to do and not have to bring in the DBAs.

**Comment by jsachs** [comment]
Closed by cd1b46b1f43c65901ced1d8cd903f44339858229
