### ISSUE TITLE
Create project view: projects are models and are linked to user hours

### ISSUE THREAD

**Issue by jsachs** [amida-tech/ration#6]

**Comment by jsachs** [comment]
@mmccall what's your expected behavior if someone deletes a Project from your project list? I like that the list is easily flexible, but we may need to replicate the Project name somehow, or at least save versions of Projects.

**Comment by mmccall** [comment]
@jsachs I just viewed the project list as a lookup for committing to the hours objects. If you delete the project, you just can't use it for making any more hours entries, but those already saved remain.  Hadn't considered any linking between a project object or hours in my design.
